# docker-compose.yml

version: "3.4"
services:
  alerts_service:
    image: consumer_2
    container_name: consumer2
    environment:
      - REDIS_HOSTNAME=redislocal
      - REDIS_PORT=6379
    networks:
      - local-dev

networks:
  local-dev:
    external: true
